# Name of your application. Used to uniquely configure containers.
service: water_resources

# Name of the container image.
image: idclofficial/water_resources

# Deploy to these servers.
servers:
  web:
    - 35.180.24.186

proxy:
  ssl: true
  host: waterresources.im.gov.ng
  app_port: 3000
  healthcheck:
    path: /

# Credentials for your image host.
registry:
  server: ghcr.io
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD

ssh:
  user: ubuntu

# Configure builder setup.
builder:
  arch: amd64
  cache:
    type: gha
  secrets:
    - KAMAL_REGISTRY_USERNAME
    - KAMAL_REGISTRY_PASSWORD
  args:
    NEXT_PUBLIC_CONTENTFUL_MINISTRY_ID: <% ENV["NEXT_PUBLIC_CONTENTFUL_MINISTRY_ID"] %>
    NEXT_PUBLIC_CONTENTFUL_SPACE_ID: <% ENV["NEXT_PUBLIC_CONTENTFUL_SPACE_ID"] %>
    NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN: <% ENV["NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN"] %>
    NEXT_PUBLIC_CONTENTFUL_PREVIEW_ACCESS_TOKEN: <% ENV["NEXT_PUBLIC_CONTENTFUL_PREVIEW_ACCESS_TOKEN"] %>
